[tool.poetry]
name = "coffee-rating-prediction-server"
version = "0.1.0"
description = ""
authors = ["Alex Haslam <alexhaslam12@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.11"
scikit-learn = "1.5.0"
numpy  = "1.23.5"
awslambdaric = "^2.0.11"
